const CONFIG = {
    STRIPE_PUBLISHABLE_KEY: window.ENV?.STRIPE_PUBLISHABLE_KEY || '',
    SUPABASE_URL: window.ENV?.SUPABASE_URL || '',
    SUPABASE_ANON_KEY: window.ENV?.SUPABASE_ANON_KEY || '',
    SMS_API_BASE: window.location.origin,
    ADMIN_PHONES: ['+19082550185', '+19143848734', '+19293629534', '+19084134836'],
    EMERGENCY_PIN: '911911',
    STRIPE_PRICE_TABLE_6: window.ENV?.STRIPE_PRICE_TABLE_6 || '',
    STRIPE_PRICE_TABLE_8: window.ENV?.STRIPE_PRICE_TABLE_8 || '',
    STRIPE_PRICE_TABLE_10: window.ENV?.STRIPE_PRICE_TABLE_10 || '',
    STRIPE_PRICE_TABLE_12: window.ENV?.STRIPE_PRICE_TABLE_12 || '',
    SF_PRESENCE_ENABLED: window.ENV?.SF_PRESENCE_ENABLED === 'true'
    ,USE_SUPABASE_PHONE_OTP: window.ENV?.USE_SUPABASE_PHONE_OTP === 'true'
};

window.CONFIG = CONFIG;
