[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

# Clean API paths → Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Force /admin → landing/login
[[redirects]]
  from = "/admin"
  to = "/widget/"
  status = 302
  force = true
