name: Link Checker

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@v2
        with:
          args: >-
            --verbose
            --no-progress
            --timeout 20
            --max-redirects 5
            'public/**/*.html'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: Generate report artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lychee-report
          path: ./lychee/out.md
