[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/send-code"
  to = "/.netlify/functions/send-code"
  status = 200

[[redirects]]
  from = "/api/verify-code"
  to = "/.netlify/functions/verify-code"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
